import homepageImage from "../../assets/homepage3.png";
const PostData = [
    {
        id: 1,
        name: "Nhà trọ ở Quận 1",
        description: "Nhà trọ tại khu vực trung tâm, gần công viên, thuận tiện đi lại.",
        price: 100,
        location: "Quận 1, TP HCM",
        score: 4.5,
        imgUrl: homepageImage,
        author: "Quản lý nhà trọ ABC",
        date: "2023-11-26",
    },
    {
        id: 2,
        name: "Căn hộ chung cư cao cấp",
        description: "Căn hộ đẳng cấp với view đẹp, nội thất sang trọng, tiện ích đầy đủ.",
        price: 150,
        location: "Quận 2, TP HCM",
        score: 4.8,
        imgUrl: homepageImage,
        author: "Chủ căn hộ XYZ",
        date: "2023-11-25",
    },
    {
        id: 3,
        name: "Nhà trọ ở Quận 1",
        description: "Nhà trọ tại khu vực trung tâm, gần công viên, thuận tiện đi lại.",
        price: 100,
        location: "Quận 1, TP HCM",
        score: 4.5,
        imgUrl: homepageImage,
        author: "Quản lý nhà trọ ABC",
        date: "2023-11-26",
    },
    {
        id: 4,
        name: "Căn hộ chung cư cao cấp",
        description: "Căn hộ đẳng cấp với view đẹp, nội thất sang trọng, tiện ích đầy đủ.",
        price: 150,
        location: "Quận 2, TP HCM",
        score: 4.8,
        imgUrl: homepageImage,
        author: "Chủ căn hộ XYZ",
        date: "2023-11-25",
    },
    {
        id: 5,
        name: "Nhà trọ ở Quận 1",
        description: "Nhà trọ tại khu vực trung tâm, gần công viên, thuận tiện đi lại.",
        price: 100,
        location: "Quận 1, TP HCM",
        score: 4.5,
        imgUrl: homepageImage,
        author: "Quản lý nhà trọ ABC",
        date: "2023-11-26",
    },
    {
        id: 6,
        name: "Căn hộ chung cư cao cấp",
        description: "Căn hộ đẳng cấp với view đẹp, nội thất sang trọng, tiện ích đầy đủ.",
        price: 150,
        location: "Quận 2, TP HCM",
        score: 4.8,
        imgUrl: homepageImage,
        author: "Chủ căn hộ XYZ",
        date: "2023-11-25",
    },
    {
        id: 7,
        name: "Nhà trọ ở Quận 1",
        description: "Nhà trọ tại khu vực trung tâm, gần công viên, thuận tiện đi lại.",
        price: 100,
        location: "Quận 1, TP HCM",
        score: 4.5,
        imgUrl: homepageImage,
        author: "Quản lý nhà trọ ABC",
        date: "2023-11-26",
    },
    {
        id: 8,
        name: "Căn hộ chung cư cao cấp",
        description: "Căn hộ đẳng cấp với view đẹp, nội thất sang trọng, tiện ích đầy đủ.",
        price: 150,
        location: "Quận 2, TP HCM",
        score: 4.8,
        imgUrl: homepageImage,
        author: "Chủ căn hộ XYZ",
        date: "2023-11-25",
    },
];

export default PostData;
